name: currency_converter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.3
  sprintf: ^7.0.0
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  flutter_svg: ^2.0.9
  injector: ^3.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  jiffy: ^6.2.1
  uuid: ^4.2.2
  app_settings: ^5.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.1
  bloc_test: ^9.1.7
  equatable: ^2.0.5
  envied: ^0.5.4+1
  http_mock_adapter: ^0.6.1
  currency_text_input_formatter: ^2.1.11
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/
