name: currency_converter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.3
  sprintf: ^7.0.0
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  flutter_svg: ^2.0.9
  injector: ^3.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  jiffy: ^6.2.1
  uuid: ^4.2.2
  app_settings: ^5.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.1
  bloc_test: ^9.1.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
