// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'currency_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CurrencyListImpl _$$CurrencyListImplFromJson(Map<String, dynamic> json) =>
    _$CurrencyListImpl(
      EUR: Currency.fromJson(json['EUR'] as Map<String, dynamic>),
      USD: Currency.fromJson(json['USD'] as Map<String, dynamic>),
      JPY: Currency.fromJson(json['JPY'] as Map<String, dynamic>),
      BGN: Currency.fromJson(json['BGN'] as Map<String, dynamic>),
      CZK: Currency.fromJson(json['CZK'] as Map<String, dynamic>),
      DKK: Currency.fromJson(json['DKK'] as Map<String, dynamic>),
      GBP: Currency.fromJson(json['GBP'] as Map<String, dynamic>),
      HUF: Currency.fromJson(json['HUF'] as Map<String, dynamic>),
      PLN: Currency.fromJson(json['PLN'] as Map<String, dynamic>),
      RON: Currency.fromJson(json['RON'] as Map<String, dynamic>),
      SEK: Currency.fromJson(json['SEK'] as Map<String, dynamic>),
      CHF: Currency.fromJson(json['CHF'] as Map<String, dynamic>),
      ISK: Currency.fromJson(json['ISK'] as Map<String, dynamic>),
      NOK: Currency.fromJson(json['NOK'] as Map<String, dynamic>),
      HRK: Currency.fromJson(json['HRK'] as Map<String, dynamic>),
      RUB: Currency.fromJson(json['RUB'] as Map<String, dynamic>),
      TRY: Currency.fromJson(json['TRY'] as Map<String, dynamic>),
      AUD: Currency.fromJson(json['AUD'] as Map<String, dynamic>),
      BRL: Currency.fromJson(json['BRL'] as Map<String, dynamic>),
      CAD: Currency.fromJson(json['CAD'] as Map<String, dynamic>),
      CNY: Currency.fromJson(json['CNY'] as Map<String, dynamic>),
      HKD: Currency.fromJson(json['HKD'] as Map<String, dynamic>),
      IDR: Currency.fromJson(json['IDR'] as Map<String, dynamic>),
      ILS: Currency.fromJson(json['ILS'] as Map<String, dynamic>),
      INR: Currency.fromJson(json['INR'] as Map<String, dynamic>),
      KRW: Currency.fromJson(json['KRW'] as Map<String, dynamic>),
      MXN: Currency.fromJson(json['MXN'] as Map<String, dynamic>),
      MYR: Currency.fromJson(json['MYR'] as Map<String, dynamic>),
      NZD: Currency.fromJson(json['NZD'] as Map<String, dynamic>),
      PHP: Currency.fromJson(json['PHP'] as Map<String, dynamic>),
      SGD: Currency.fromJson(json['SGD'] as Map<String, dynamic>),
      THB: Currency.fromJson(json['THB'] as Map<String, dynamic>),
      ZAR: Currency.fromJson(json['ZAR'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$CurrencyListImplToJson(_$CurrencyListImpl instance) =>
    <String, dynamic>{
      'EUR': instance.EUR,
      'USD': instance.USD,
      'JPY': instance.JPY,
      'BGN': instance.BGN,
      'CZK': instance.CZK,
      'DKK': instance.DKK,
      'GBP': instance.GBP,
      'HUF': instance.HUF,
      'PLN': instance.PLN,
      'RON': instance.RON,
      'SEK': instance.SEK,
      'CHF': instance.CHF,
      'ISK': instance.ISK,
      'NOK': instance.NOK,
      'HRK': instance.HRK,
      'RUB': instance.RUB,
      'TRY': instance.TRY,
      'AUD': instance.AUD,
      'BRL': instance.BRL,
      'CAD': instance.CAD,
      'CNY': instance.CNY,
      'HKD': instance.HKD,
      'IDR': instance.IDR,
      'ILS': instance.ILS,
      'INR': instance.INR,
      'KRW': instance.KRW,
      'MXN': instance.MXN,
      'MYR': instance.MYR,
      'NZD': instance.NZD,
      'PHP': instance.PHP,
      'SGD': instance.SGD,
      'THB': instance.THB,
      'ZAR': instance.ZAR,
    };
